name: Feature Request
description: Suggest a new feature for the WISP project
labels: [enchancement]
body:
  - type: markdown
    attributes:
      value: |
        This is purely for frontend-related feature requests - requests like subdomain manager, etc. are currently better suited for our [Discord](https://wisp.gg/discord) instead.

        Please [search here](https://github.com/wisp-gg/frontend/issues?q=is%3Aissue) to see if someone else has already suggested this.

  - type: textarea
    attributes:
      label: Describe the feature and why you would like to see it.
      description: A clear & concise description of the feature you'd like to have added, and what issues it would solve.
      placeholder: I would like to see the server widget to display the server short UUID for easier identification
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like.
      description: Explain how you would like to see the feature implemented.
      placeholder: Display server short UUID in the server widget
    validations:
      required: true

  - type: textarea
    attributes:
      label: Optional additional context to this request.
      description: Provide optional context or screenshots about the feature request.
    validations:
      required: false
